var units = new Array ("Zero", "ookan",
"Eéji",
"ẹẹ́ta",
"ẹẹ́rin",
"aárùn",
"ẹẹ́fà",
"eéje",
"ẹ̀jọ",
"ẹẹ́sàn",
"ẹẹ́wà",
"oókànlá",
"eéjìlá",
"ẹẹ́talá",
"ẹẹ́rìnlá",
"ẹ́ẹdógún",
"ẹẹ́rìndílógún",
"eétàdílógún",
"eéjìdílógún",
"oókàndílógún",
"ogún",
"Ọkanlelogun",
"Ejilelogun",
"Ẹtalelogun",
"Ẹrinlelogun",
 "ẹ́ẹdọ́gbọ̀n",
"Ẹrindinlọgbọn",
"Ẹtadinlọgbọn",
"Ejidinlọgbọn",
"Ọkandinlọgbọn",
"Ọgbọn",
"Ọkanlelọgbọn",
"Ejilelọgbọn",
"Ẹtalelọgbọn",
"Ẹrinlelọgbọn",
"aárùndílogójì",
"Ẹrindinlogoji",
"Ẹtadinlogoji",
"Ejidinlogoji",
"Ọkandinlogoji",
"Ogoji",
"Ọkanlelogoji",
"Ejilelogoji",
"Ẹtalelogoji",
"Ẹrinlelogoji",
"Arundinladọta",
"Ẹrindinladọta",
"Ẹtadinladọta",
"Ejidinladọta",
"Ọkandinladọta",
"àádọ́ta",
"Ọkanleladọta",
"Ejileladọta",
"Ẹtaleladọta",
"Ẹrinleladọta",
"Arundinlọgọta",
"Ẹrindinlọgọta",
"Ẹtadinlọgọta",
"Ejidinlọgọta",
"Ọkandinlọgọta",
"Ọgọta",
"Ọkanlelọgọta",
"Ejilelọgọta",
"Ẹtalelọgọta",
"Ẹrinlelọgọta",
"Arundiladọrin",
"mẹ́rìndínláàdọ́rin",
"mẹ́tàdínláàdọ́rin",
"méjídínláàdọ́rin",
"mọ́kàndínláàdọ́rin",
"àádọ́rin",
"Ọkanleladọrin",
"Ejileladọrin",
"Ẹtaleladọrin",
"Ẹrinleladọrin",
"Arundilọgọrin",
"Ẹrindilọgọrin",
"Ẹtadilọgọrin",
"Ejidilọgọrin",
"Ọkandilọgọrin",
"Ọgọrin",
"Ọkanlelọgọrin",
"Ejilelọgọrin",
"Ẹtalelọgọrin",
"Ẹrinlelọgọrin",
"Arundiladọrun",
"Ẹrindiladọrun",
"Ẹtadiladọrun",
"Ejidiladọrun",
"Ọkandiladọrun",
"àádọ́rùn",
"Ọkanleladọrun",
"Ejileladọrun",
"Ẹtaleladọrun",
"Ẹrinleladọrun",
"Arundilọgọrun",
"Ẹrindilọgọrun",
"Ẹtadilọgọrun",
"Ejidilọgọrun",
"Ọkandilọgọrun",
"ọgọ́rùn",
"mọ́kànlélọ́gọ́rùn",
"méjìlélọ́gọ́rùn",
"mẹ́tàlélọ́gọ́rùn",
"mẹ́rìnlélọ́gọ́rùn",
"márùndínláàdọ́fà",
"mẹ́rìndínláàdọ́fà",
"mẹ́tàdínláàdọ́fà",
"méjìdínláàdọ́fà",
"mọ́kàndínláàdọ́fà",
"àádọ́fà",
"mọ́kànléláàdọ́fà",
"méjìléláàdọ́fà",
"mẹ́tàléláàdọ́fà",
"mẹ́rìnléláàdọ́fà",
"márùndínlọ́gọ́fà",
"mẹ́rìndínlọ́gọ́fà",
"mẹ́tàdínlọ́gọ́fà",
"méjídínlọ́gọ́fà",
"mọ́kàndínlọ́gọ́fà",
"ọgọ́fà",
"mọ́kànlélọ́gọ́fà",
"méjìlélọ́gọ́fà",
"mẹ́tàlélọ́gọ́fà",
"mẹ́rìnlélọ́gọ́fà",
"márùndínláàdóje",
"mẹ́rìndínláàdóje",
"mẹ́tàdínláàdóje",
"méjìdínláàdóje",
"mọ́kàndínláàdọ́fà",
"àádóje",
"mọ́kànlélàádóje",
"méjìlélàádóje",
"mẹ́tàlélàádóje",
"mẹ́rìnlélàádóje",
"márùndínlógóje",
"mẹ́rìndínlógóje",
"mẹ́tàdínlógóje",
"méjídínlógóje",
"mọ́kàndínlógóje",
"ogóje",
"mọ́kànlélógóje",
"méjìlélógóje",
"mẹ́tàlélógóje",
"mẹ́rìnlélógóje",
"márùndínláàdọ́jọ",
"mẹ́rìndínláàdọ́jọ",
"mẹ́tàdínláàdọ́jọ",
"méjídínláàdọ́jọ",
"mọ́kàndínláàdọ́jọ",
"àádọ́jọ",
"mọ́kànléláàdọ́jọ",
"méjìléláàdọ́jọ",
"mẹ́tàléláàdọ́jọ",
"mẹ́rìnléláàdọ́jọ",
"márùndínlọgọ́jọ",
"mẹ́rìndínlọgọ́jọ",
"mẹ́tàdínlọgọ́jọ",
"méjídínlọgọ́jọ",
"mọ́kàndínlọ́gọ́jọ",
"ọgọ́jọ",
"mọ́kànlélọ́gọ́jọ",
"méjìlélọ́gọ́jọ",
"mẹ́tàlélọ́gọ́jọ",
"mẹ́rìnlélọ́gọ́jọ",
"márùndínláàdọ́sàn",
"mẹ́rìndínláàdọ́sàn",
"mẹ́tàdínláàdọ́sàn",
"méjídínláàdọ́sàn",
"mọ́kàndínláàdọ́sàn",
"àádọ́sàn",
"mọ́kànléláàdọ́sàn",
"méjìléláàdọ́sàn",
"mẹ́tàléláàdọ́sàn",
"mẹ́rìnléláàdọ́sàn",
"márùndínlọ́gọ́sàn",
"mẹ́rìndínlọ́gọ́sàn",
"mẹ́tàdínlọ́gọ́sàn",
"méjídínlọ́gọ́sàn",
"mọ́kàndínlọ́gọ́sàn",
"ọgọ́sàn",
"mọ́kànlélọ́gọ́sàn",
"méjìlélọ́gọ́sàn",
"mẹ́tàlélọ́gọ́sàn",
"mẹ́rìnlélọ́gọ́sàn",
"márùndínláàdọ́wàá",
"mẹ́rìndínláàdọ́wàá",
"mẹ́tàdínláàdọ́wàá",
"méjídínláàdọ́wàá",
"mọ́kàndínláàdọ́wàá",
"àádọ́wàá",
"mọ́kànléláàdọ́wàá",
"méjìléláàdọ́wàá",
"mẹ́tàléláàdọ́wàá",
"mẹ́rìnléláàdọ́wàá",
"márùndínnígba",
"mẹ́rìndínnígba",
"mẹ́tàdínnígba",
"méjídínnígba",
"mọ́kàndínnígba",
"igba",
"mọ́kànlènígba",
"méjìlènígba",
"mẹ́tàlènígba",
"mẹ́rìnlènígba",
"márùndínláàdọ́fà",
"mẹ́rìndínláàdọ́fà",
"mẹ́tàdínláàdọ́fà",
"méjídínláàdọ́fà",
"mọ́kàndínláàdọ́fà",
"àádọ́fà",
"okòólénígba dín mẹ́san",
"okòólénígba dín mẹjo",
"okòólénígba dín meje",
"okòólénígba dín mẹ́fa",
"okòólénígba dín marun",
"okòólénígba dín mẹ́rìn",
"okòólénígba dín mẹ́tà",
"okòólénígba dín méjí",
"okòólénígba dín kàn",
"okòólénígba",
"okòólénígba le kan",
"okòólénígba àti méjí",
"okòólénígba àti mẹ́tà",
"okòólénígba àti mẹ́rìn",
"okòólénígba àti marùn",
"okòólénígba àti mẹ́fà",
"okòólénígba àti meje",
"okòólénígba àti mẹjọ",
"okòólénígba àti mẹsan",
"okòólénígba àti mẹwàá",
"òjìlénígba dín mẹ́sàn",
"òjìlénígba dín mẹ́jọ",
"òjìlénígba dín meje",
"òjìlénígba dín mẹfa",
"òjìlènígba dín marun",
"òjìlènígba dín mẹrin",
"òjìlènígba dín mẹta",
"òjìlènígba dín meji",
"òjìlènígba dín ọkan",
"òjìlérúgba",
"òjìlénígba lé kan",
"òjìlénígba lé meji",
"òjìlénígba lé meta",
"òjìlénígba lé merin",
"òjìlénígba lé marun",
"òjìlénígba lé mefa",
"òjìlénígba lé meje",
"òjìlénígba lé mejo",
"òjìlénígba lé mesan",
"òjìlénígba lé mewaa",
"ọ̀tàlénígba din mesan",
"ọ̀tàlénígba din mejo",
"ọ̀tàlénígba din meje",
"ọ̀tàlénígba din mefa",
"ọ̀tàlénígba din marun",
"ọ̀tàlénígba din merin",
"ọ̀tàlénígba din meta",
"ọ̀tàlénígba din meji",
"ọ̀tàlénígba din kan",
"ọ̀tàlénígba",
"ọ̀tàlénígba lé kan",
"ọ̀tàlénígba lé meji",
"ọ̀tàlénígba lé mẹta",
"ọ̀tàlénígba lé mẹrin",
"ọ̀tàlénígba le marun",
"ọ̀tàlénígba le mẹfa",
"ọ̀tàlénígba le meje",
"ọ̀tàlénígba le mẹjo",
"ọ̀tàlénígba le mẹsan",
"ọ̀tàlénígba le mẹwaa",
"ọ̀rìnlénígba din mẹsan",
"ọ̀rìnlénígba din mẹjo",
"ọ̀rìnlénígba din meje",
"ọ̀rìnlénígba din mẹfa",
"ọ̀rìnlénígba din marun",
"ọ̀rìnlénígba din mẹrin",
"ọ̀rìnlénígba din mẹta",
"ọ̀rìnlénígba din meji",
"ọ̀rìnlénígba din kan",
"ọ̀rìnlénígba",
"ọ̀rìnlénígba lé kan",
"ọ̀rìnlénígba lé meji",
"ọ̀rìnlénígba lé meta",
"ọ̀rìnlénígba lé merin",
"ọ̀rìnlénígba lé marun",
"ọ̀rìnlénígba lé mefa",
"ọ̀rìnlénígba lé meje",
"ọ̀rìnlénígba lé mejo",
"ọ̀rìnlénígba lé mesan",
"ọ̀rìnlénígba lé mewaa",
"ọ́ọ̀dúnrún dín mesan",
"ọ́ọ̀dúnrún dín mẹjo",
"ọ́ọ̀dúnrún dín meje",
"ọ́ọ̀dúnrún dín mẹfa",
"ọ́ọ̀dúnrún dín marun",
"ọ́ọ̀dúnrún dín mẹrin",
"ọ́ọ̀dúnrún dín mẹta",
"ọ́ọ̀dúnrún dín meji",
"ọ́ọ̀dúnrún dín kan",
"ọ́ọ̀dúnrún",
"mọ́kànlèniọ́ọ̀dúnrún",
"méjìlèniọ́ọ̀dúnrún",
"mẹ́tàlèniọ́ọ̀dúnrún",
"mẹ́rìnlèniọ́ọ̀dúnrún",
"márùnléniọ́ọ̀dúnrún",
"mefaléniọ́ọ̀dúnrún",
"mejeléniọ́ọ̀dúnrún",
"mẹjọléniọ́ọ̀dúnrún",
"mẹsanléniọ́ọ̀dúnrún",
"mẹwàáléniọ́ọ̀dúnrún",
"okòóléniọ́ọ̀dúnrún dín mẹ́san",
"okòóléniọ́ọ̀dúnrún dín mẹjo",
"okòóléniọ́ọ̀dúnrún dín meje",
"okòóléniọ́ọ̀dúnrún dín mẹ́fa",
"okòóléniọ́ọ̀dúnrún dín marun",
"okòóléniọ́ọ̀dúnrún dín mẹ́rìn",
"okòóléniọ́ọ̀dúnrún dín mẹ́tà",
"okòóléniọ́ọ̀dúnrún dín méjí",
"okòóléniọ́ọ̀dúnrún dín kàn",
"okòóléniọ́ọ̀dúnrún",
"okòóléniọ́ọ̀dúnrún le kan",
"okòóléniọ́ọ̀dúnrún àti méjí",
"okòóléniọ́ọ̀dúnrún àti mẹ́tà",
"okòóléniọ́ọ̀dúnrún àti mẹ́rìn",
"okòóléníọ́ọ̀dúnrún àti marùn",
"okòóléníọ́ọ̀dúnrún àti mẹ́fà",
"okòóléníọ́ọ̀dúnrún àti meje",
"okòóléníọ́ọ̀dúnrún àti mẹjọ",
"okòóléníọ́ọ̀dúnrún àti mẹsan",
"okòóléníọ́ọ̀dúnrún àti mẹwàá",
"òjìléníọ́ọ̀dúnrún dín mẹ́sàn",
"òjìléníọ́ọ̀dúnrún dín mẹ́jọ",
"òjìléníọ́ọ̀dúnrún dín meje",
"òjìléníọ́ọ̀dúnrún dín mẹfa",
"òjìlèníọ́ọ̀dúnrún dín marun",
"òjìlèníọ́ọ̀dúnrún dín mẹrin",
"òjìlèníọ́ọ̀dúnrún dín mẹta",
"òjìlèníọ́ọ̀dúnrún dín meji",
"òjìlèníọ́ọ̀dúnrún dín ọkan",
"òjìlérọ́ọ̀dúnrún",
"òjìléníọ́ọ̀dúnrún lé kan",
"òjìléníọ́ọ̀dúnrún lé meji",
"òjìléníọ́ọ̀dúnrún lé meta",
"òjìléníọ́ọ̀dúnrún lé merin",
"òjìléníọ́ọ̀dúnrún lé marun",
"òjìléníọ́ọ̀dúnrún lé mefa",
"òjìléníọ́ọ̀dúnrún lé meje",
"òjìléníọ́ọ̀dúnrún lé mejo",
"òjìléníọ́ọ̀dúnrún lé mesan",
"òjìléníọ́ọ̀dúnrún lé mewaa",
"ọ̀tàléníọ́ọ̀dúnrún din mesan",
"ọ̀tàléníọ́ọ̀dúnrún din mejo",
"ọ̀tàléníọ́ọ̀dúnrún din meje",
"ọ̀tàléníọ́ọ̀dúnrún din mefa",
"ọ̀tàléníọ́ọ̀dúnrún din marun",
"ọ̀tàléníọ́ọ̀dúnrún din merin",
"ọ̀tàléníọ́ọ̀dúnrún din meta",
"ọ̀tàléníọ́ọ̀dúnrún din meji",
"ọ̀tàléníọ́ọ̀dúnrún din kan",
"ọ̀tàléníọ́ọ̀dúnrún",
"ọ̀tàléníọ́ọ̀dúnrún lé kan",
"ọ̀tàléníọ́ọ̀dúnrún lé meji",
"ọ̀tàléníọ́ọ̀dúnrún lé mẹta",
"ọ̀tàléníọ́ọ̀dúnrún lé mẹrin",
"ọ̀tàléníọ́ọ̀dúnrún le marun",
"ọ̀tàléníọ́ọ̀dúnrún le mẹfa",
"ọ̀tàléníọ́ọ̀dúnrún le meje",
"ọ̀tàléníọ́ọ̀dúnrún le mẹjo",
"ọ̀tàléníọ́ọ̀dúnrún le mẹsan",
"ọ̀tàléníọ́ọ̀dúnrún le mẹwaa",
"ọ̀rìnléníọ́ọ̀dúnrún din mẹsan",
"ọ̀rìnléníọ́ọ̀dúnrún din mẹjo",
"ọ̀rìnléníọ́ọ̀dúnrún din meje",
"ọ̀rìnléníọ́ọ̀dúnrún din mẹfa",
"ọ̀rìnléníọ́ọ̀dúnrún din marun",
"ọ̀rìnléníọ́ọ̀dúnrún din mẹrin",
"ọ̀rìnléníọ́ọ̀dúnrún din mẹta",
"ọ̀rìnléníọ́ọ̀dúnrún din meji",
"ọ̀rìnléníọ́ọ̀dúnrún din kan",
"ọ̀rìnléníọ́ọ̀dúnrún",
"ọ̀rìnléníọ́ọ̀dúnrún lé kan",
"ọ̀rìnléníọ́ọ̀dúnrún lé meji",
"ọ̀rìnléníọ́ọ̀dúnrún lé meta",
"ọ̀rìnléníọ́ọ̀dúnrún lé merin",
"ọ̀rìnléníọ́ọ̀dúnrún lé marun",
"ọ̀rìnléníọ́ọ̀dúnrún lé mefa",
"ọ̀rìnléníọ́ọ̀dúnrún lé meje",
"ọ̀rìnléníọ́ọ̀dúnrún lé mejo",
"ọ̀rìnléníọ́ọ̀dúnrún lé mesan",
"ọ̀rìnléníọ́ọ̀dúnrún lé mewaa",
"irinwó dín mesan",
"irinwó dín mẹjo",
"irinwó dín meje",
"irinwó dín mẹfa",
"irinwó dín marun",
"irinwó dín mẹrin",
"irinwó dín mẹta",
"irinwó dín meji",
"irinwó dín kan",
"irinwó",
"mokanlenirinwó",
"méjìlèniirinwó",
"mẹ́tàlèniirinwó",
"mẹ́rìnlèniirinwó",
"márùnléniirinwó",
"mefaléniirinwó",
"mejeléniirinwó",
"mẹjọléniirinwó",
"mẹsanléniirinwó",
"mẹwàáléniirinwó",
"okòóléniirinwó dín mẹ́san",
"okòóléniirinwó dín mẹjo",
"okòóléniirinwó dín meje",
"okòóléniirinwó dín mẹ́fa",
"okòóléniirinwó dín marun",
"okòóléniirinwó dín mẹ́rìn",
"okòóléniirinwó dín mẹ́tà",
"okòóléniirinwó dín méjí",
"okòóléniirinwó dín kàn",
"okòóléniirinwó",
"okòóléniirinwó le kan",
"okòóléniirinwó àti méjí",
"okòóléniirinwó àti mẹ́tà",
"okòóléniirinwó àti mẹ́rìn",
"okòóléníirinwó àti marùn",
"okòóléníirinwó àti mẹ́fà",
"okòóléníirinwó àti meje",
"okòóléníirinwó àti mẹjọ",
"okòóléníirinwó àti mẹsan",
"okòóléníirinwó àti mẹwàá",
"òjìléníirinwó dín mẹ́sàn",
"òjìléníirinwó dín mẹ́jọ",
"òjìléníirinwó dín meje",
"òjìléníirinwó dín mẹfa",
"òjìlèníirinwó dín marun",
"òjìlèníirinwó dín mẹrin",
"òjìlèníirinwó dín mẹta",
"òjìlèníirinwó dín meji",
"òjìlèníirinwó dín ọkan",
"òjìléririnwó",
"òjìléníirinwó lé kan",
"òjìléníirinwó lé meji",
"òjìléníirinwó lé meta",
"òjìléníirinwó lé merin",
"òjìléníirinwó lé marun",
"òjìléníirinwó lé mefa",
"òjìléníirinwó lé meje",
"òjìléníirinwó lé mejo",
"òjìléníirinwó lé mesan",
"òjìléníirinwó lé mewaa",
"ọ̀tàléníirinwó din mesan",
"ọ̀tàléníirinwó din mejo",
"ọ̀tàléníirinwó din meje",
"ọ̀tàléníirinwó din mefa",
"ọ̀tàléníirinwó din marun",
"ọ̀tàléníirinwó din merin",
"ọ̀tàléníirinwó din meta",
"ọ̀tàléníirinwó din meji",
"ọ̀tàléníirinwó din kan",
"ọ̀tàléníirinwó",
"ọ̀tàléníirinwó lé kan",
"ọ̀tàléníirinwó lé meji",
"ọ̀tàléníirinwó lé mẹta",
"ọ̀tàléníirinwó lé mẹrin",
"ọ̀tàléníirinwó le marun",
"ọ̀tàléníirinwó le mẹfa",
"ọ̀tàléníirinwó le meje",
"ọ̀tàléníirinwó le mẹjo",
"ọ̀tàléníirinwó le mẹsan",
"ọ̀tàléníirinwó le mẹwaa",
"ọ̀rìnléníirinwó din mẹsan",
"ọ̀rìnléníirinwó din mẹjo",
"ọ̀rìnléníirinwó din meje",
"ọ̀rìnléníirinwó din mẹfa",
"ọ̀rìnléníirinwó din marun",
"ọ̀rìnléníirinwó din mẹrin",
"ọ̀rìnléníirinwó din mẹta",
"ọ̀rìnléníirinwó din meji",
"ọ̀rìnléníirinwó din kan",
"ọ̀rìnléníirinwó",
"ọ̀rìnléníirinwó lé kan",
"ọ̀rìnléníirinwó lé meji",
"ọ̀rìnléníirinwó lé meta",
"ọ̀rìnléníirinwó lé merin",
"ọ̀rìnléníirinwó lé marun",
"ọ̀rìnléníirinwó lé mefa",
"ọ̀rìnléníirinwó lé meje",
"ọ̀rìnléníirinwó lé mejo",
"ọ̀rìnléníirinwó lé mesan",
"ọ̀rìnléníirinwó lé mewaa",
"ẹ̀ẹ́dẹ́gbẹ̀ta dín mesan",
"ẹ̀ẹ́dẹ́gbẹ̀ta dín mẹjo",
"ẹ̀ẹ́dẹ́gbẹ̀ta dín meje",
"ẹ̀ẹ́dẹ́gbẹ̀ta dín mẹfa",
"ẹ̀ẹ́dẹ́gbẹ̀ta dín marun",
"ẹ̀ẹ́dẹ́gbẹ̀ta dín mẹrin",
"ẹ̀ẹ́dẹ́gbẹ̀ta dín mẹta",
"ẹ̀ẹ́dẹ́gbẹ̀ta dín meji",
"ẹ̀ẹ́dẹ́gbẹ̀ta dín kan",
"ẹ̀ẹ́dẹ́gbẹ̀ta",
"mọ́kànlèniẹ̀ẹ́dẹ́gbẹ̀ta",
"méjìlèniẹ̀ẹ́dẹ́gbẹ̀ta",
"mẹ́tàlèniẹ̀ẹ́dẹ́gbẹ̀ta",
"mẹ́rìnlèniẹ̀ẹ́dẹ́gbẹ̀ta",
"márùnléniẹ̀ẹ́dẹ́gbẹ̀ta",
"mefaléniẹ̀ẹ́dẹ́gbẹ̀ta",
"mejeléniẹ̀ẹ́dẹ́gbẹ̀ta",
"mẹjọléniẹ̀ẹ́dẹ́gbẹ̀ta",
"mẹsanléniẹ̀ẹ́dẹ́gbẹ̀ta",
"mẹwàáléniẹ̀ẹ́dẹ́gbẹ̀ta",
"okòóléniẹ̀ẹ́dẹ́gbẹ̀ta dín mẹ́san",
"okòóléniẹ̀ẹ́dẹ́gbẹ̀ta dín mẹjo",
"okòóléniẹ̀ẹ́dẹ́gbẹ̀ta dín meje",
"okòóléniẹ̀ẹ́dẹ́gbẹ̀ta dín mẹ́fa",
"okòóléniẹ̀ẹ́dẹ́gbẹ̀ta dín marun",
"okòóléniẹ̀ẹ́dẹ́gbẹ̀ta dín mẹ́rìn",
"okòóléniẹ̀ẹ́dẹ́gbẹ̀ta dín mẹ́tà",
"okòóléniẹ̀ẹ́dẹ́gbẹ̀ta dín méjí",
"okòóléniẹ̀ẹ́dẹ́gbẹ̀ta dín kàn",
"okòóléniẹ̀ẹ́dẹ́gbẹ̀ta",
"okòóléniẹ̀ẹ́dẹ́gbẹ̀ta le kan",
"okòóléniẹ̀ẹ́dẹ́gbẹ̀ta àti méjí",
"okòóléniẹ̀ẹ́dẹ́gbẹ̀ta àti mẹ́tà",
"okòóléniẹ̀ẹ́dẹ́gbẹ̀ta àti mẹ́rìn",
"okòóléníẹ̀ẹ́dẹ́gbẹ̀ta àti marùn",
"okòóléníẹ̀ẹ́dẹ́gbẹ̀ta àti mẹ́fà",
"okòóléníẹ̀ẹ́dẹ́gbẹ̀ta àti meje",
"okòóléníẹ̀ẹ́dẹ́gbẹ̀ta àti mẹjọ",
"okòóléníẹ̀ẹ́dẹ́gbẹ̀ta àti mẹsan",
"okòóléníẹ̀ẹ́dẹ́gbẹ̀ta àti mẹwàá",
"òjìléníẹ̀ẹ́dẹ́gbẹ̀ta dín mẹ́sàn",
"òjìléníẹ̀ẹ́dẹ́gbẹ̀ta dín mẹ́jọ",
"òjìléníẹ̀ẹ́dẹ́gbẹ̀ta dín meje",
"òjìléníẹ̀ẹ́dẹ́gbẹ̀ta dín mẹfa",
"òjìlèníẹ̀ẹ́dẹ́gbẹ̀ta dín marun",
"òjìlèníẹ̀ẹ́dẹ́gbẹ̀ta dín mẹrin",
"òjìlèníẹ̀ẹ́dẹ́gbẹ̀ta dín mẹta",
"òjìlèníẹ̀ẹ́dẹ́gbẹ̀ta dín meji",
"òjìlèníẹ̀ẹ́dẹ́gbẹ̀ta dín ọkan",
"òjìlérẹ̀ẹ́dẹ́gbẹ̀ta",
"òjìléníẹ̀ẹ́dẹ́gbẹ̀ta lé kan",
"òjìléníẹ̀ẹ́dẹ́gbẹ̀ta lé meji",
"òjìléníẹ̀ẹ́dẹ́gbẹ̀ta lé meta",
"òjìléníẹ̀ẹ́dẹ́gbẹ̀ta lé merin",
"òjìléníẹ̀ẹ́dẹ́gbẹ̀ta lé marun",
"òjìléníẹ̀ẹ́dẹ́gbẹ̀ta lé mefa",
"òjìléníẹ̀ẹ́dẹ́gbẹ̀ta lé meje",
"òjìléníẹ̀ẹ́dẹ́gbẹ̀ta lé mejo",
"òjìléníẹ̀ẹ́dẹ́gbẹ̀ta lé mesan",
"òjìléníẹ̀ẹ́dẹ́gbẹ̀ta lé mewaa",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta din mesan",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta din mejo",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta din meje",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta din mefa",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta din marun",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta din merin",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta din meta",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta din meji",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta din kan",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta lé kan",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta lé meji",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta lé mẹta",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta lé mẹrin",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta le marun",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta le mẹfa",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta le meje",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta le mẹjo",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta le mẹsan",
"ọ̀tàléníẹ̀ẹ́dẹ́gbẹ̀ta le mẹwaa",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta din mẹsan",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta din mẹjo",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta din meje",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta din mẹfa",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta din marun",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta din mẹrin",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta din mẹta",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta din meji",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta din kan",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta lé kan",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta lé meji",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta lé meta",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta lé merin",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta lé marun",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta lé mefa",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta lé meje",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta lé mejo",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta lé mesan",
"ọ̀rìnléníẹ̀ẹ́dẹ́gbẹ̀ta lé mewaa",
"ẹgbẹ̀ta dín mesan",
"ẹgbẹ̀ta dín mẹjo",
"ẹgbẹ̀ta dín meje",
"ẹgbẹ̀ta dín mẹfa",
"ẹgbẹ̀ta dín marun",
"ẹgbẹ̀ta dín mẹrin",
"ẹgbẹ̀ta dín mẹta",
"ẹgbẹ̀ta dín meji",
"ẹgbẹ̀ta dín kan",
"ẹgbẹ̀ta",
"mọ́kànlènieẹgbẹ̀ta",
"méjìlèniẹegbẹ̀ta",
"mẹ́tàlèniẹegbẹ̀ta",
"mẹ́rìnlèniẹegbẹ̀ta",
"márùnléniẹegbẹ̀ta",
"mefaléniẹegbẹ̀ta",
"mejeléniẹegbẹ̀ta",
"mẹjọléniẹegbẹ̀ta",
"mẹsanlénieẹgbẹ̀ta",
"mẹwàáléniẹegbẹ̀ta",
"okòóléniẹegbẹ̀ta dín mẹ́san",
"okòóléniẹegbẹ̀ta dín mẹjo",
"okòóléniẹegbẹ̀ta dín meje",
"okòólénieẹgbẹ̀ta dín mẹ́fa",
"okòólénieẹgbẹ̀ta dín marun",
"okòólénieẹgbẹ̀ta dín mẹ́rìn",
"okòólénieẹgbẹ̀ta dín mẹ́tà",
"okòólénieẹgbẹ̀ta dín méjí",
"okòólénieẹgbẹ̀ta dín kàn",
"okòólénieẹgbẹ̀ta",
"okòólénieẹgbẹ̀ta le kan",
"okòólénieẹgbẹ̀ta àti méjí",
"okòólénieẹgbẹ̀ta àti mẹ́tà",
"okòólénieẹgbẹ̀ta àti mẹ́rìn",
"okòóléníẹegbẹ̀ta àti marùn",
"okòóléníẹegbẹ̀ta àti mẹ́fà",
"okòóléníẹegbẹ̀ta àti meje",
"okòóléníẹegbẹ̀ta àti mẹjọ",
"okòóléníẹegbẹ̀ta àti mẹsan",
"okòóléníẹegbẹ̀ta àti mẹwàá",
"òjìléníẹegbẹ̀ta dín mẹ́sàn",
"òjìléníẹegbẹ̀ta dín mẹ́jọ",
"òjìléníẹegbẹ̀ta dín meje",
"òjìléníẹegbẹ̀ta dín mẹfa",
"òjìlèníẹegbẹ̀ta dín marun",
"òjìlèníẹegbẹ̀ta dín mẹrin",
"òjìlèníẹegbẹ̀ta dín mẹta",
"òjìlèníẹegbẹ̀ta dín meji",
"òjìlèníẹegbẹ̀ta dín ọkan",
"òjìlérẹegbẹ̀ta",
"òjìléníẹegbẹ̀ta lé kan",
"òjìléníẹegbẹ̀ta lé meji",
"òjìléníẹegbẹ̀ta lé meta",
"òjìléníẹegbẹ̀ta lé merin",
"òjìléníẹegbẹ̀ta lé marun",
"òjìléníẹegbẹ̀ta lé mefa",
"òjìléníẹegbẹ̀ta lé meje",
"òjìléníẹegbẹ̀ta lé mejo",
"òjìléníeẹgbẹ̀ta lé mesan",
"òjìléníeẹgbẹ̀ta lé mewaa",
"ọ̀tàléníeẹgbẹ̀ta din mesan",
"ọ̀tàléníeẹgbẹ̀ta din mejo",
"ọ̀tàléníeẹgbẹ̀ta din meje",
"ọ̀tàléníeẹgbẹ̀ta din mefa",
"ọ̀tàléníeẹgbẹ̀ta din marun",
"ọ̀tàléníeẹgbẹ̀ta din merin",
"ọ̀tàléníeẹgbẹ̀ta din meta",
"ọ̀tàléníeẹgbẹ̀ta din meji",
"ọ̀tàléníeẹgbẹ̀ta din kan",
"ọ̀tàléníeẹgbẹ̀ta",
"ọ̀tàléníeẹgbẹ̀ta lé kan",
"ọ̀tàléníeẹgbẹ̀ta lé meji",
"ọ̀tàléníeẹgbẹ̀ta lé mẹta",
"ọ̀tàléníeẹgbẹ̀ta lé mẹrin",
"ọ̀tàléníeẹgbẹ̀ta le marun",
"ọ̀tàléníeẹgbẹ̀ta le mẹfa",
"ọ̀tàléníeẹgbẹ̀ta le meje",
"ọ̀tàléníeẹgbẹ̀ta le mẹjo",
"ọ̀tàléníeẹgbẹ̀ta le mẹsan",
"ọ̀tàlénieẹgbẹ̀ta le mẹwaa",
"ọ̀rìnlénieẹgbẹ̀ta din mẹsan",
"ọ̀rìnlénieẹgbẹ̀ta din mẹjo",
"ọ̀rìnlénieẹgbẹ̀ta din meje",
"ọ̀rìnlénieẹgbẹ̀ta din mẹfa",
"ọ̀rìnlénieẹgbẹ̀ta din marun",
"ọ̀rìnlénieẹgbẹ̀ta din mẹrin",
"ọ̀rìnlénieẹgbẹ̀ta din mẹta",
"ọ̀rìnlénieẹgbẹ̀ta din meji",
"ọ̀rìnlénieẹgbẹ̀ta din kan",
"ọ̀rìnlénieẹgbẹ̀ta",
"ọ̀rìnlénieẹgbẹ̀ta lé kan",
"ọ̀rìnlénieẹgbẹ̀ta lé meji",
"ọ̀rìnlénieẹgbẹ̀ta lé meta",
"ọ̀rìnlénieẹgbẹ̀ta lé merin",
"ọ̀rìnlénieẹgbẹ̀ta lé marun",
"ọ̀rìnlénieẹgbẹ̀ta lé mefa",
"ọ̀rìnlénieẹgbẹ̀ta lé meje",
"ọ̀rìnlénieẹgbẹ̀ta lé mejo",
"ọ̀rìnlénieẹgbẹ̀ta lé mesan",
"ọ̀rìnlénieẹgbẹ̀ta lé mewaa",
"ẹ̀ẹ́dẹ̀gbẹ̀rin dín mesan",
"ẹ̀ẹ́dẹ̀gbẹ̀rin dín mẹjo",
"ẹ̀ẹ́dẹ̀gbẹ̀rin dín meje",
"ẹ̀ẹ́dẹ̀gbẹ̀rin dín mẹfa",
"ẹ̀ẹ́dẹ̀gbẹ̀rin dín marun",
"ẹ̀ẹ́dẹ̀gbẹ̀rin dín mẹrin",
"ẹ̀ẹ́dẹ̀gbẹ̀rin dín mẹta",
"ẹ̀ẹ́dẹ̀gbẹ̀rin dín meji",
"ẹ̀ẹ́dẹ̀gbẹ̀rin dín kan",
"ẹ̀ẹ́dẹ̀gbẹ̀rin",
"mọ́kànlèniẹ̀ẹ́dẹ̀gbẹ̀rin",
"méjìlèniẹ̀ẹ́dẹ̀gbẹ̀rin",
"mẹ́tàlèniẹ̀ẹ́dẹ̀gbẹ̀rin",
"mẹ́rìnlèniẹ̀ẹ́dẹ̀gbẹ̀rin",
"márùnléniẹ̀ẹ́dẹ̀gbẹ̀rin",
"mefaléniẹ̀ẹ́dẹ̀gbẹ̀rin",
"mejeléniẹ̀ẹ́dẹ̀gbẹ̀rin",
"mẹjọléniẹ̀ẹ́dẹ̀gbẹ̀rin",
"mẹsanléniẹ̀ẹ́dẹ̀gbẹ̀rin",
"mẹwàáléniẹ̀ẹ́dẹ̀gbẹ̀rin",
"okòóléniẹ̀ẹ́dẹ̀gbẹ̀rin dín mẹ́san",
"okòóléniẹ̀ẹ́dẹ̀gbẹ̀rin dín mẹjo",
"okòóléniẹ̀ẹ́dẹ̀gbẹ̀rin dín meje",
"okòóléniẹ̀ẹ́dẹ̀gbẹ̀rin dín mẹ́fa",
"okòóléniẹ̀ẹ́dẹ̀gbẹ̀rin dín marun",
"okòóléniẹ̀ẹ́dẹ̀gbẹ̀rin dín mẹ́rìn",
"okòóléniẹ̀ẹ́dẹ̀gbẹ̀rin dín mẹ́tà",
"okòóléniẹ̀ẹ́dẹ̀gbẹ̀rin dín méjí",
"okòóléniẹ̀ẹ́dẹ̀gbẹ̀rin dín kàn",
"okòóléniẹ̀ẹ́dẹ̀gbẹ̀rin",
"okòóléniẹ̀ẹ́dẹ̀gbẹ̀rin le kan",
"okòóléniẹ̀ẹ́dẹ̀gbẹ̀rin àti méjí",
"okòóléniẹ̀ẹ́dẹ̀gbẹ̀rin àti mẹ́tà",
"okòóléniẹ̀ẹ́dẹ̀gbẹ̀rin àti mẹ́rìn",
"okòóléníẹ̀ẹ́dẹ̀gbẹ̀rin àti marùn",
"okòóléníẹ̀ẹ́dẹ̀gbẹ̀rin àti mẹ́fà",
"okòóléníẹ̀ẹ́dẹ̀gbẹ̀rin àti meje",
"okòóléníẹ̀ẹ́dẹ̀gbẹ̀rin àti mẹjọ",
"okòóléníẹ̀ẹ́dẹ̀gbẹ̀rin àti mẹsan",
"okòóléníẹ̀ẹ́dẹ̀gbẹ̀rin àti mẹwàá",
"òjìléníẹ̀ẹ́dẹ̀gbẹ̀rin dín mẹ́sàn",
"òjìléníẹ̀ẹ́dẹ̀gbẹ̀rin dín mẹ́jọ",
"òjìléníẹ̀ẹ́dẹ̀gbẹ̀rin dín meje",
"òjìléníẹ̀ẹ́dẹ̀gbẹ̀rin dín mẹfa",
"òjìlèníẹ̀ẹ́dẹ̀gbẹ̀rin dín marun",
"òjìlèníẹ̀ẹ́dẹ̀gbẹ̀rin dín mẹrin",
"òjìlèníẹ̀ẹ́dẹ̀gbẹ̀rin dín mẹta",
"òjìlèníẹ̀ẹ́dẹ̀gbẹ̀rin dín meji",
"òjìlèníẹ̀ẹ́dẹ̀gbẹ̀rin dín ọkan",
"òjìlérẹ̀ẹ́dẹ̀gbẹ̀rin",
"òjìléníẹ̀ẹ́dẹ̀gbẹ̀rin lé kan",
"òjìléníẹ̀ẹ́dẹ̀gbẹ̀rin lé meji",
"òjìléníẹ̀ẹ́dẹ̀gbẹ̀rin lé meta",
"òjìléníẹ̀ẹ́dẹ̀gbẹ̀rin lé merin",
"òjìléníẹ̀ẹ́dẹ̀gbẹ̀rin lé marun",
"òjìléníẹ̀ẹ́dẹ̀gbẹ̀rin lé mefa",
"òjìléníẹ̀ẹ́dẹ̀gbẹ̀rin lé meje",
"òjìléníẹ̀ẹ́dẹ̀gbẹ̀rin lé mejo",
"òjìléníẹ̀ẹ́dẹ̀gbẹ̀rin lé mesan",
"òjìléníẹ̀ẹ́dẹ̀gbẹ̀rin lé mewaa",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin din mesan",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin din mejo",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin din meje",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin din mefa",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin din marun",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin din merin",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin din meta",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin din meji",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin din kan",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin lé kan",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin lé meji",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin lé mẹta",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin lé mẹrin",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin le marun",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin le mẹfa",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin le meje",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin le mẹjo",
"ọ̀tàléníẹ̀ẹ́dẹ̀gbẹ̀rin le mẹsan",
"ọ̀tàléniẹ̀ẹ́dẹ̀gbẹ̀rin le mẹwaa",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin din mẹsan",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin din mẹjo",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin din meje",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin din mẹfa",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin din marun",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin din mẹrin",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin din mẹta",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin din meji",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin din kan",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin lé kan",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin lé meji",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin lé meta",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin lé merin",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin lé marun",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin lé mefa",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin lé meje",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin lé mejo",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin lé mesan",
"ọ̀rìnléniẹ̀ẹ́dẹ̀gbẹ̀rin lé mewaa",
"ẹgbẹ̀rin dín mesan",
"ẹgbẹ̀rin dín mẹjo",
"ẹgbẹ̀rin dín meje",
"ẹgbẹ̀rin dín mẹfa",
"ẹgbẹ̀rin dín marun",
"ẹgbẹ̀rin dín mẹrin",
"ẹgbẹ̀rin dín mẹta",
"ẹgbẹ̀rin dín meji",
"ẹgbẹ̀rin dín kan",
"ẹgbẹ̀rin",
"mọ́kànlèniẹgbẹ̀rin",
"méjìlèniẹgbẹ̀rin",
"mẹ́tàlèniẹgbẹ̀rin",
"mẹ́rìnlèniẹgbẹ̀rin",
"márùnléniẹgbẹ̀rin",
"mefaléniẹgbẹ̀rin",
"mejeléniẹgbẹ̀rin",
"mẹjọléniẹgbẹ̀rin",
"mẹsanléniẹgbẹ̀rin",
"mẹwàáléniẹgbẹ̀rin",
"okòóléniẹgbẹ̀rin dín mẹ́san",
"okòóléniẹgbẹ̀rin dín mẹjo",
"okòóléniẹgbẹ̀rin dín meje",
"okòóléniẹgbẹ̀rin dín mẹ́fa",
"okòóléniẹgbẹ̀rin dín marun",
"okòóléniẹgbẹ̀rin dín mẹ́rìn",
"okòóléniẹgbẹ̀rin dín mẹ́tà",
"okòóléniẹgbẹ̀rin dín méjí",
"okòóléniẹgbẹ̀rin dín kàn",
"okòóléniẹgbẹ̀rin",
"okòóléniẹgbẹ̀rin le kan",
"okòóléniẹgbẹ̀rin àti méjí",
"okòóléniẹgbẹ̀rin àti mẹ́tà",
"okòóléniẹgbẹ̀rin àti mẹ́rìn",
"okòóléníẹgbẹ̀rin àti marùn",
"okòóléníẹgbẹ̀rin àti mẹ́fà",
"okòóléníẹgbẹ̀rin àti meje",
"okòóléníẹgbẹ̀rin àti mẹjọ",
"okòóléníẹgbẹ̀rin àti mẹsan",
"okòóléníẹgbẹ̀rin àti mẹwàá",
"òjìléníẹgbẹ̀rin dín mẹ́sàn",
"òjìléníẹgbẹ̀rin dín mẹ́jọ",
"òjìléníẹgbẹ̀rin dín meje",
"òjìléníẹgbẹ̀rin dín mẹfa",
"òjìlèníẹgbẹ̀rin dín marun",
"òjìlèníẹgbẹ̀rin dín mẹrin",
"òjìlèníẹgbẹ̀rin dín mẹta",
"òjìlèníẹgbẹ̀rin dín meji",
"òjìlèníẹgbẹ̀rin dín ọkan",
"òjìlérẹegbẹ̀rin",
"òjìléníẹgbẹ̀rin lé kan",
"òjìléníẹgbẹ̀rin lé meji",
"òjìléníẹgbẹ̀rin lé meta",
"òjìléníẹgbẹ̀rin lé merin",
"òjìléníẹgbẹ̀rin lé marun",
"òjìléníẹgbẹ̀rin lé mefa",
"òjìléníẹgbẹ̀rin lé meje",
"òjìléníẹgbẹ̀rin lé mejo",
"òjìléniẹgbẹ̀rin lé mesan",
"òjìléníẹgbẹ̀rin lé mewaa",
"ọ̀tàléníẹgbẹ̀rin din mesan",
"ọ̀tàléníẹgbẹ̀rin din mejo",
"ọ̀tàléníẹgbẹ̀rin din meje",
"ọ̀tàléníẹgbẹ̀rin din mefa",
"ọ̀tàléníẹgbẹ̀rin din marun",
"ọ̀tàléníẹgbẹ̀rin din merin",
"ọ̀tàléníẹgbẹ̀rin din meta",
"ọ̀tàléníẹgbẹ̀rin din meji",
"ọ̀tàléníẹgbẹ̀rin din kan",
"ọ̀tàléníẹgbẹ̀rin",
"ọ̀tàléníẹgbẹ̀rin lé kan",
"ọ̀tàléníẹgbẹ̀rin lé meji",
"ọ̀tàléníẹgbẹ̀rin lé mẹta",
"ọ̀tàléníẹgbẹ̀rin lé mẹrin",
"ọ̀tàléníẹgbẹ̀rin le marun",
"ọ̀tàléníẹgbẹ̀rin le mẹfa",
"ọ̀tàléníẹgbẹ̀rin le meje",
"ọ̀tàléníẹgbẹ̀rin le mẹjo",
"ọ̀tàléníẹgbẹ̀rin le mẹsan",
"ọ̀tàléniẹgbẹ̀rin le mẹwaa",
"ọ̀rìnléniẹgbẹ̀rin din mẹsan",
"ọ̀rìnléniẹgbẹ̀rin din mẹjo",
"ọ̀rìnléniẹgbẹ̀rin din meje",
"ọ̀rìnléniẹgbẹ̀rin din mẹfa",
"ọ̀rìnléniẹgbẹ̀rin din marun",
"ọ̀rìnléniẹgbẹ̀rin din mẹrin",
"ọ̀rìnléniẹgbẹ̀rin din mẹta",
"ọ̀rìnléniẹgbẹ̀rin din meji",
"ọ̀rìnléniẹgbẹ̀rin din kan",
"ọ̀rìnléniẹgbẹ̀rin",
"ọ̀rìnléniẹgbẹ̀rin lé kan",
"ọ̀rìnléniẹgbẹ̀rin lé meji",
"ọ̀rìnléniẹgbẹ̀rin lé meta",
"ọ̀rìnléniẹgbẹ̀rin lé merin",
"ọ̀rìnléniẹgbẹ̀rin lé marun",
"ọ̀rìnléniẹgbẹ̀rin lé mefa",
"ọ̀rìnléniẹgbẹ̀rin lé meje",
"ọ̀rìnléniẹgbẹ̀rin lé mejo",
"ọ̀rìnléniẹgbẹ̀rin lé mesan",
"ọ̀rìnléniẹgbẹ̀rin lé mewaa",
"ẹ̀ẹ́dẹ́gbàárun dín mesan",
"ẹ̀ẹ́dẹ́gbàárun dín mẹjo",
"ẹ̀ẹ́dẹ́gbàárun dín meje",
"ẹ̀ẹ́dẹ́gbàárun dín mẹfa",
"ẹ̀ẹ́dẹ́gbàárun dín marun",
"ẹ̀ẹ́dẹ́gbàárun dín mẹrin",
"ẹ̀ẹ́dẹ́gbàárun dín mẹta",
"ẹ̀ẹ́dẹ́gbàárun dín meji",
"ẹ̀ẹ́dẹ́gbàárun dín kan",
"ẹ̀ẹ́dẹ́gbàárun",
"mọ́kànlèniẹ̀ẹ́dẹ́gbàárun",
"méjìlèniẹ̀ẹ́dẹ́gbàárun",
"mẹ́tàlèniẹ̀ẹ́dẹ́gbàárun",
"mẹ́rìnlèniẹ̀ẹ́dẹ́gbàárun",
"márùnléniẹ̀ẹ́dẹ́gbàárun",
"mefaléniẹ̀ẹ́dẹ́gbàárun",
"mejeléniẹ̀ẹ́dẹ́gbàárun",
"mẹjọléniẹ̀ẹ́dẹ́gbàárun",
"mẹsanléniẹ̀ẹ́dẹ́gbàárun",
"mẹwàáléniẹ̀ẹ́dẹ́gbàárun",
"okòóléniẹ̀ẹ́dẹ́gbàárun dín mẹ́san",
"okòóléniẹ̀ẹ́dẹ́gbàárun dín mẹjo",
"okòóléniẹ̀ẹ́dẹ́gbàárun dín meje",
"okòóléniẹ̀ẹ́dẹ́gbàárun dín mẹ́fa",
"okòóléniẹ̀ẹ́dẹ́gbàárun dín marun",
"okòóléniẹ̀ẹ́dẹ́gbàárun dín mẹ́rìn",
"okòóléniẹ̀ẹ́dẹ́gbàárun dín mẹ́tà",
"okòóléniẹ̀ẹ́dẹ́gbàárun dín méjí",
"okòóléniẹ̀ẹ́dẹ́gbàárun dín kàn",
"okòóléniẹ̀ẹ́dẹ́gbàárun",
"okòóléniẹ̀ẹ́dẹ́gbàárun le kan",
"okòóléniẹ̀ẹ́dẹ́gbàárun àti méjí",
"okòóléniẹ̀ẹ́dẹ́gbàárun àti mẹ́tà",
"okòóléniẹ̀ẹ́dẹ́gbàárun àti mẹ́rìn",
"okòóléníẹ̀ẹ́dẹ́gbàárun àti marùn",
"okòóléníẹ̀ẹ́dẹ́gbàárun àti mẹ́fà",
"okòóléníẹ̀ẹ́dẹ́gbàárun àti meje",
"okòóléníẹ̀ẹ́dẹ́gbàárun àti mẹjọ",
"okòóléníẹ̀ẹ́dẹ́gbàárun àti mẹsan",
"okòóléníẹ̀ẹ́dẹ́gbàárun àti mẹwàá",
"òjìléníẹ̀ẹ́dẹ́gbàárun dín mẹ́sàn",
"òjìléníẹ̀ẹ́dẹ́gbàárun dín mẹ́jọ",
"òjìléníẹ̀ẹ́dẹ́gbàárun dín meje",
"òjìléníẹ̀ẹ́dẹ́gbàárun dín mẹfa",
"òjìlèníẹ̀ẹ́dẹ́gbàárun dín marun",
"òjìlèníẹ̀ẹ́dẹ́gbàárun dín mẹrin",
"òjìlèníẹ̀ẹ́dẹ́gbàárun dín mẹta",
"òjìlèníẹ̀ẹ́dẹ́gbàárun dín meji",
"òjìlèníẹ̀ẹ́dẹ́gbàárun dín ọkan",
"òjìlérẹẹ̀ẹ́dẹ́gbàárun",
"òjìléníẹ̀ẹ́dẹ́gbàárun lé kan",
"òjìléníẹ̀ẹ́dẹ́gbàárun lé meji",
"òjìléníẹ̀ẹ́dẹ́gbàárun lé meta",
"òjìléníẹ̀ẹ́dẹ́gbàárun lé merin",
"òjìléníẹ̀ẹ́dẹ́gbàárun lé marun",
"òjìléníẹ̀ẹ́dẹ́gbàárun lé mefa",
"òjìléníẹ̀ẹ́dẹ́gbàárun lé meje",
"òjìléníẹ̀ẹ́dẹ́gbàárun lé mejo",
"òjìléniẹ̀ẹ́dẹ́gbàárun lé mesan",
"òjìléníẹ̀ẹ́dẹ́gbàárun lé mewaa",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun din mesan",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun din mejo",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun din meje",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun din mefa",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun din marun",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun din merin",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun din meta",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun din meji",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun din kan",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun lé kan",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun lé meji",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun lé mẹta",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun lé mẹrin",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun le marun",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun le mẹfa",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun le meje",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun le mẹjo",
"ọ̀tàléníẹ̀ẹ́dẹ́gbàárun le mẹsan",
"ọ̀tàléniẹ̀ẹ́dẹ́gbàárun le mẹwaa",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun din mẹsan",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun din mẹjo",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun din meje",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun din mẹfa",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun din marun",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun din mẹrin",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun din mẹta",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun din meji",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun din kan",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun lé kan",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun lé meji",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun lé meta",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun lé merin",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun lé marun",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun lé mefa",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun lé meje",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun lé mejo",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun lé mesan",
"ọ̀rìnléniẹ̀ẹ́dẹ́gbàárun lé mewaa",
"ẹ̀gbẹ̀rún dín mesan",
"ẹ̀gbẹ̀rún dín mẹjo",
"ẹ̀gbẹ̀rún dín meje",
"ẹ̀gbẹ̀rún dín mẹfa",
"ẹ̀gbẹ̀rún dín marun",
"ẹ̀gbẹ̀rún dín mẹrin",
"ẹ̀gbẹ̀rún dín mẹta",
"ẹ̀gbẹ̀rún dín meji",
"ẹ̀gbẹ̀rún dín kan",
"ẹ̀gbẹ̀rún");
var tens = new Array ("Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety");
function num(it) {
	var theword = "";
	var started;	
	for (var i=1; i <= 1000; i++) {
		if (it==i) {
			theword += (started?units[i].toLowerCase():units[i]);
		}
	};
	return theword;
}